# Generate .env file for bash scripts to source
# This allows scripts to use values from terraform.tfvars instead of hardcoding

resource "local_file" "terraform_env" {
  filename = "${path.module}/scripts/.env"

  content = <<-EOT
    # Auto-generated by Terraform - DO NOT EDIT MANUALLY
    # Source: terraform/config-export.tf
    # Generated from: terraform.tfvars

    # Database Configuration
    export DB_NAME="${var.db_name}"
    export DB_USER="${var.db_user}"
    export DB_PASSWORD="${var.db_password}"
    export DB_VERSION="${var.db_version}"
    export DB_PLAN="${var.db_plan}"

    # Application Configuration
    export BACKEND_PORT="${var.backend_port}"
    export FRONTEND_PORT="${var.frontend_port}"

    # Infrastructure Configuration
    export VM_PLAN="${var.vm_plan}"
    export IMAGE_NAME="${var.image_name}"
    export SSH_KEY_NAME="${var.ssh_key_name}"

    # Network Configuration
    export VPC_CIDR_DELHI="${var.vpc_cidr_delhi}"
    export VPC_CIDR_CHENNAI="${var.vpc_cidr_chennai}"

    # Repository Configuration
    export GITHUB_REPO_URL="${var.github_repo_url}"
  EOT

  file_permission = "0600"
}

output "env_file_location" {
  description = "Location of generated environment file for scripts"
  value       = local_file.terraform_env.filename
}
